#pragma once
#include "glm/vec2.hpp"

namespace Terrain {
enum class BlockType {
    CactusInside,
    CactusSide,
    CactusTop,
    CottonBlue,
    CottonBrown,
    CottonGreen,
    CottonRed,
    CottonTan,
    Dirt,
    DirtGrass,
    DirtSand,
    DirtSnow,
    Grass1,
    Grass2,
    Grass3,
    Grass4,
    GrassBrown,
    GrassTan,
    GrassTop,
    GrassTopJungle,
    GrassTopTundra,
    GravelDirt,
    GravelStone,
    Greysand,
    Greystone,
    GreystoneSand,
    Ice,
    Lava,
    Leaves,
    LeavesOrange,
    LeavesOrangeTransparent,
    LeavesTransparent,
    Redsand,
    Redstone,
    RedstoneSand,
    Rock,
    RockMoss,
    Sand,
    Snow,
    Stone,
    StoneDirt,
    StoneGrass,
    StoneSand,
    StoneSnow,
    TrunkSide,
    TrunkTop,
    TrunkWhiteSide,
    TrunkWhiteTop,
    Water,
};

glm::vec2 GetTextPos(BlockType blockType);

float GetBaseHeight(const glm::vec2& pos);
} // namespace Terrain
